<?php echo $this->doctype() ?>
<html>
<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>
</head>
<style>
  footer {
      text-align: center;
      position:absolute;
      bottom:0;
      width:100%;
      height:80px;
      background:#ABD2E7;
      font-size: 15px;
        }	

  a{
      text-decoration: none;
    }

  a:link {
      color: #000000;
    }

  a:visited {
      color: #000000;
    }

  a:hover {
      color: #000000;
    }

  a:active {
      color: #000000;
    }

ul {
    	font: bold 26px/18px sans-serif;
      text-align: center;
      display: inline;
      margin: 0;
      padding: 25px 4px 17px 0;
      list-style: none;
       /*text-align: center;*/
      -webkit-box-shadow: 0 0 5px rgba(0, 0, 0, 0.15);
      -moz-box-shadow: 0 0 5px rgba(0, 0, 0, 0.15);
      box-shadow: 0 0 5px rgba(0, 0, 0, 0.15);
  }

ul li {
      font: bold 20px/18px sans-serif;
      display: inline-block;
      margin-right: -4px;
      position: relative;
      padding: 15px 20px;
      background: #ABD2E7;
      cursor: pointer;
      -webkit-transition: all 0.2s;
      -moz-transition: all 0.2s;
      -ms-transition: all 0.2s;
      -o-transition: all 0.2s;
      transition: all 0.2s;
    }

ul li:hover {
      background: #285066;
    }

ul li ul {
      padding: 0;
      position: absolute;
      top: 48px;
      left: 0;
      width: 150px;
      -webkit-box-shadow: none;
      -moz-box-shadow: none;
      box-shadow: none;
      display: none;
      opacity: 0;
      visibility: hidden;
      -webkit-transiton: opacity 0.2s;
      -moz-transition: opacity 0.2s;
      -ms-transition: opacity 0.2s;
      -o-transition: opacity 0.2s;
      -transition: opacity 0.2s;
      }

ul li ul li { 
      display: block; 
      color: #000000;
      font: bold 15px/18px sans-serif;
      
    }

ul li ul li:hover { 
      background: #8B6767; 
    }

ul li:hover ul {
      display: block;
      opacity: 1;
      visibility: visible;
    }
    body
    {
    	background: #EEEAF3; 
    }

	</style>
<body >
    <center>
      <div class="row">
        <div class="col-md-6">
            <nav>
              <ul>
                <li><a href="/Blog/public">Home</a></li>
                <li><a href="/Blog/public/Users/profile">Profile</a></li>
                <li><a href="/Blog/public/Category/index">Categories</a></li>
                <li><a href="/Blog/public/Users/login">Log in</a></li>
                
              </ul>
            </nav>  
          <br>
          <br>
        </div>	
      </div>
    </center> 
      <?php echo $this->layout()->content ?>
        </div>
         <div class="col-md-3">
          <div class="footer">
     	      <footer>
              <p>CopyRights: AmErA</p>
              <p>Contact information: <a href="mailto:amera.elsayed6@gmail.com">Blog@AmErA.com</a>.</p>
            </footer> 
          </div>
        </div>
      </div> 
</body>
</html> 